### PR TITLE
WAS-1048 Five figure Easting or Northing postcode lookup causes error

### PR DESCRIPTION
**Pull request by autotelik**
Fix formatting of x,y from address facade to handle any possibility

### CODE REVIEW

**Comment by timstone** [comment]
@Cruikshanks QA passed, over to you @Cruikshanks for PR

**Comment by Cruikshanks** [comment]
Passing this back to you until the niggle with Shetland postcodes is resolved. For a test you can use *ZE2 9SD* as a postcode which should return X & Y's like `"x":"442779.0","y":"1144563.0"`, and this should convert into *HU 42779 44563*.

**Comment by autotelik** [comment]
@Cruikshanks So handled 7 digit y .. we sure we don't wanna do something similar for x ?

**Comment by Cruikshanks** [comment]
@autotelik Yep. If you go back to the [grid](https://en.wikipedia.org/wiki/Ordnance_Survey_National_Grid) NGR's are based on x doesn't go into double digits, so you can always take it for granted that if its greater than 6 chars its because its trying to give you silly levels of accuracy!

**Pull request merged**
